# Loader Metadata
modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
issueTrackerURL = "https://github.com/TitanForgeIndustries/Primal-Winter-Reimagined/issues"

[[mods]]
    modId = "primalwinter"
    version = "${file.jarVersion}"
    displayName = "Primal Winter: Reimagined"
    displayURL = "https://www.curseforge.com/minecraft/mc-mods/primal-winter-reimagined"
    logoFile = "logo.png"
    authors = "AlcatrazEscapee, GhostTapp"
    description = '''A reimagined take on Primal Winter that locks the world in a brutal, atmospheric blizzard with a configurable start day and enhanced snow, fog, and ambience.'''

[[dependencies.primalwinter]]
    modId = "forge"
    mandatory = true
    versionRange = "[47,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.primalwinter]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1, 1.21)"
    ordering = "NONE"
    side = "BOTH"
